function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Tuple{typeof(MbedTLS.ssl_read), MbedTLS.SSLContext, Ptr{UInt8}, UInt64})
    precompile(Tuple{typeof(MbedTLS.ssl_get_bytes_avail), MbedTLS.SSLContext})
    precompile(Tuple{typeof(MbedTLS.ssl_write), MbedTLS.SSLContext, Ptr{UInt8}, UInt64})
    precompile(Tuple{typeof(MbedTLS.crt_parse), String})
    precompile(Tuple{typeof(MbedTLS.hostname!), MbedTLS.SSLContext, Base.SubString{String}})
    precompile(Tuple{typeof(MbedTLS.ssl_session_reset), MbedTLS.SSLContext})
    precompile(Tuple{typeof(MbedTLS.mbed_err), Int32})
    precompile(Tuple{typeof(MbedTLS.ssl_close_notify), MbedTLS.SSLContext})
    precompile(Tuple{typeof(MbedTLS.ssl_check_pending), MbedTLS.SSLContext})
    precompile(Tuple{typeof(MbedTLS.ssl_handshake), MbedTLS.SSLContext})
    precompile(Tuple{typeof(MbedTLS.f_send), Ptr{Nothing}, Ptr{UInt8}, UInt64})
    precompile(Tuple{typeof(MbedTLS.ssl_set_bio), MbedTLS.SSLContext, Ptr{Nothing}, Ptr{Nothing}, Ptr{Nothing}})
    precompile(Tuple{typeof(MbedTLS.f_rng), MbedTLS.CtrDrbg, Ptr{UInt8}, UInt64})
    precompile(Tuple{typeof(MbedTLS.f_recv), Ptr{Nothing}, Ptr{UInt8}, UInt64})
    precompile(Tuple{typeof(MbedTLS.ssl_unsafe_write), MbedTLS.SSLContext, Ptr{UInt8}, UInt64})
    precompile(Tuple{typeof(MbedTLS.wait_for_encrypted_data), MbedTLS.SSLContext})
    precompile(Tuple{typeof(MbedTLS.__init__)})
    precompile(Tuple{typeof(MbedTLS.ssl_unsafe_read), MbedTLS.SSLContext, Ptr{UInt8}, UInt64})
    precompile(Tuple{typeof(MbedTLS.wait_for_decrypted_data), MbedTLS.SSLContext})
    precompile(Tuple{getfield(MbedTLS, Symbol("##SSLConfig#46")), Nothing, Type{Int}, Bool})
    precompile(Tuple{typeof(MbedTLS.ssl_setup), MbedTLS.SSLContext, MbedTLS.SSLConfig})
    precompile(Tuple{typeof(MbedTLS.ca_chain!), MbedTLS.SSLConfig})
    precompile(Tuple{typeof(MbedTLS.ssl_abandon), MbedTLS.SSLContext})
    precompile(Tuple{typeof(MbedTLS.handshake), MbedTLS.SSLContext})
end
